### ISSUE TITLE
Options to wait for presence of xpath or selector

### ISSUE THREAD

**Issue by alex-kowalczyk** [mingalevme/screenshoter#16]
The four `--wait-until-event` events provided by Puppeeteer/Screenshotter are not always the ideal choice, for instance when thumbnailing complicated vector map. 

It would be great to have additional options: `--wait-for-selector` and/or `--wait-for-xpath` which would wait for specific element to be present, specified by Xpath and/or CSS. This would allow developers to programmatically signal exactly when the page is really ready for screenshotting by just adding matching element to DOM.

When specified, the new options could add `Page.waitForSelector`/`Page.waitForXPath` calls (with provided selector/xpath and --delay timeout) instead of current pure `setTimeout` delay.

**Comment by mingalevme** [comment]
Added in version 2.0.0: wait-for-selector, wait-for-xpath, wait-for-function:

```bash
docker pull mingalevme/screenshoter
docker run --rm -p 8080:8080  mingalevme/screenshoter
`

Open "http://localhost:8080/take?wait-until-event=load&navigation-timeout-ms=5000&wait-for-selector=%23partial-discussion-header&url=https%3A%2F%2Fgithub.com%2Fmingalevme%2Fscreenshoter%2Fissues%2F16"

**Comment by alex-kowalczyk** [comment]
Tested wait-for-selector, works great!
